version: "3.9"

services:

  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - ./firefly_upload:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - db
    networks:
      - proxy
      - internal

  db:
    image: mariadb:10.6
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - ./firefly_db:/var/lib/mysql
    networks:
      - internal

  cron:
    image: alpine
    container_name: firefly_iii_cron
    restart: unless-stopped
    command: >
      sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/6125927d2f1f502e2d38bd897ebefe75\"
      | crontab - && crond -f -L /dev/stdout"
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: true
